name: Simple Android Phone
on: workflow_dispatch

jobs:
  android:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
    - name: Start Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 33
        arch: x86_64
        profile: pixel_4
        target: google_apis
        emulator-options: -no-window -gpu off -no-audio -no-boot-anim
        script: |
          # Wait for emulator to be ready
          adb wait-for-device
          echo "Emulator is running"
          # Keep the emulator running
          sleep infinity
          
    - name: Setup Web Access
      run: |
        # Install VNC and web interface
        sudo apt update
        sudo apt install -y x11vnc novnc websockify
        
        # Setup display (emulator runs on :0)
        export DISPLAY=:0
        
        # Start VNC server
        x11vnc -display :0 -forever -shared -nopw -listen localhost &
        
        # Start noVNC
        websockify --web /usr/share/novnc/ 6080 localhost:5900 &
        
    - name: Start Cloudflare Tunnel
      run: |
        wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared-linux-amd64.deb
        
        echo "🎯 ANDROID PHONE READY!"
        echo "📱 Connect via the URL below:"
        cloudflared tunnel --url http://localhost:6080
