name: Docker Android Phone
on: workflow_dispatch

jobs:
  android:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
    - name: Start Android in Docker with Web UI
      run: |
        # Pull and run Android with web interface
        docker run -d \
          --name android-phone \
          --privileged \
          -v /dev/kvm:/dev/kvm \
          -p 6080:6080 \
          -p 5554:5554 \
          -p 5555:5555 \
          -e DEVICE="Pixel 4" \
          -e APK="/apk/app-debug.apk" \
          -e EMULATOR_ARGS="-no-window -gpu off -no-audio" \
          -e TURN_OFF_SCREEN=false \
          budtmo/docker-android:latest
          
        # Wait for boot
        sleep 120
        echo "Android phone should be ready at port 6080"
        
    - name: Expose via Cloudflare
      run: |
        wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared-linux-amd64.deb
        
        echo "📱 ANDROID PHONE ACCESSIBLE VIA:"
        cloudflared tunnel --url http://localhost:6080
