name: Standalone Android Phone via Cloud
on: workflow_dispatch

jobs:
  android-phone:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install Android Emulator
      run: |
        # Install SDK tools and platform tools
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "emulator"
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-33;google_apis;x86_64"
        
        # Accept licenses
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        
        # Create AVD
        $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd \
          -n android-phone \
          -k "system-images;android-33;google_apis;x86_64" \
          -d "pixel_4" \
          --force
          
        echo "Android emulator setup complete"
        
    - name: Start Android Phone
      run: |
        # Start emulator with proper path
        $ANDROID_HOME/emulator/emulator -avd android-phone -no-window -no-boot-anim -no-audio -gpu swiftshader_indirect &
        EMULATOR_PID=$!
        
        # Wait for boot with timeout
        echo "Waiting for Android to boot..."
        timeout 180 $ANDROID_HOME/platform-tools/adb wait-for-device
        
        # Check if device is ready
        $ANDROID_HOME/platform-tools/adb devices
        echo "Android phone is booted and ready!"
        
        # Wait a bit more for system to stabilize
        sleep 30
        
    - name: Setup Web Interface
      run: |
        # Install dependencies
        sudo apt update
        sudo apt install -y xvfb novnc websockify x11vnc
        
        # Start virtual display
        Xvfb :1 -screen 0 1024x768x24 &
        export DISPLAY=:1
        
        # Start VNC server
        x11vnc -display :1 -forever -shared -nopw -listen localhost &
        
        # Start noVNC web server
        websockify --web /usr/share/novnc/ 6080 localhost:5900 &
        
        echo "Web interface setup complete"
        
    - name: Start Cloudflare Tunnel
      run: |
        # Install cloudflared
        wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared-linux-amd64.deb
        
        echo "=== ANDROID PHONE READY ==="
        echo "Connect via the URL below in your browser!"
        echo "You'll get a full Android phone interface!"
        cloudflared tunnel --url http://localhost:6080
