name: Optimized Windows RDP for MuMu Emulator

on:
  workflow_dispatch: # Manual trigger only

jobs:
  optimized-rdp-mumu:
    runs-on: windows-latest
    timeout-minutes: 3600 # 60 hour maximum

    steps:
    - name: Enable Virtualization and Hyper-V
      run: |
        Write-Host "=== ENABLING VIRTUALIZATION ==="
        # Enable Hyper-V platform
        Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All -NoRestart
        # Enable Hypervisor
        bcdedit /set hypervisorlaunchtype auto
        Write-Host "Virtualization features enabled"

    - name: Optimize System Performance
      run: |
        Write-Host "=== OPTIMIZING SYSTEM PERFORMANCE ==="
        
        # Set to high performance power plan
        powercfg /setactive SCHEME_MIN
        
        # Disable visual effects for better performance
        Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects" -Name "VisualFXSetting" -Value 2
        
        # Optimize for background services
        Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\PriorityControl" -Name "Win32PrioritySeparation" -Value 18
        
        # Disable unnecessary animations
        Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" -Name "ListviewAlphaSelect" -Value 0
        Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" -Name "ListviewShadow" -Value 0
        Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" -Name "TaskbarAnimations" -Value 0
        
        Write-Host "System performance optimized"

    - name: Configure Virtual Memory
      run: |
        Write-Host "=== CONFIGURING VIRTUAL MEMORY ==="
        
        # Use PowerShell commands instead of WMI for page file configuration
        $computer = Get-CimInstance -ClassName Win32_ComputerSystem
        Write-Host "Current automatic page file: $($computer.AutomaticManagedPagefile)"
        
        # Disable automatic page file management using registry
        Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management" -Name "PagingFiles" -Value "C:\pagefile.sys 8192 16384"
        
        # Set page file configuration directly in registry
        Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management" -Name "PagingFiles" -Value "C:\pagefile.sys 8192 16384" -Force
        
        Write-Host "Virtual memory configured (8GB-16GB)"

    - name: Configure RDP Settings
      run: |
        Write-Host "=== CONFIGURING RDP SETTINGS ==="
        
        # Enable Remote Desktop
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
        
        # Disable NLA for easier connection
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
        
        # Configure Windows Firewall
        netsh advfirewall firewall set rule group="remote desktop" new enable=Yes
        
        # Restart Terminal Services
        Restart-Service -Name TermService -Force
        
        Write-Host "RDP configured and enabled"

    - name: Optimize RDP for Graphics Performance
      run: |
        Write-Host "=== OPTIMIZING RDP GRAPHICS ==="
        
        # Improve RDP graphics performance
        Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "MaxMonitors" -Value 4
        Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "MaxXResolution" -Value 2560
        Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "MaxYResolution" -Value 1440
        
        # Enable WDDM driver for better graphics
        Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "fEnableWddmDriver" -Value 1
        
        # Increase RDP bandwidth limits
        Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "MaxBandwidth" -Value 0xffffffff
        
        Write-Host "RDP graphics optimized"

    - name: Create RDP User with Fixed Password
      run: |
        Write-Host "=== CREATING RDP USER ==="
        
        # Use fixed password as requested
        $password = "Jalingo@1"
        
        Write-Host "Using fixed password: $password"
        
        $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
        
        # Create user with password
        New-LocalUser -Name "RDPUser" -Password $securePassword -AccountNeverExpires
        
        # Add to required groups
        Add-LocalGroupMember -Group "Administrators" -Member "RDPUser"
        Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDPUser"
        
        # Store credentials in environment
        echo "RDP_USER=RDPUser" >> $env:GITHUB_ENV
        echo "RDP_PASSWORD=$password" >> $env:GITHUB_ENV
        
        Write-Host "RDP user created successfully"
        Write-Host "Username: RDPUser"
        Write-Host "Password: $password"

    - name: Download MuMu Installer
      run: |
        Write-Host "=== DOWNLOADING MUMU INSTALLER ==="
        
        # Download MuMu Emulator using the direct link
        $mumuUrl = "https://a11.gdl.netease.com/MuMu_5.0.4_gw-win-download_all_1756402042.exe?n=MuMu_5.0.4_r9kVqqC.exe"
        Write-Host "Downloading MuMu installer from: $mumuUrl"
        
        Invoke-WebRequest -Uri $mumuUrl -OutFile "MuMu_Installer.exe" -UserAgent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
        
        Write-Host "✅ MuMu installer downloaded successfully as 'MuMu_Installer.exe'"

    - name: Download MuMu Data File
      run: |
        Write-Host "=== DOWNLOADING MUMU DATA FILE ==="
        
        # Download the MuMu data file
        $mumuDataUrl = "https://github.com/binahmad362/glowing-guide/raw/refs/heads/main/Android%20Device.mumudata?download="
        Write-Host "Downloading MuMu data file from: $mumuDataUrl"
        
        Invoke-WebRequest -Uri $mumuDataUrl -OutFile "Android_Device.mumudata" -UserAgent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
        
        Write-Host "✅ MuMu data file downloaded successfully as 'Android_Device.mumudata'"

    - name: Install Cloudflared
      run: |
        Write-Host "=== INSTALLING CLOUDFLARED ==="
        
        # Download cloudflared
        Invoke-WebRequest -Uri "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe" -OutFile "cloudflared.exe"
        
        Write-Host "Cloudflared downloaded successfully"

    - name: Start Cloudflare Tunnel and Keep Alive
      run: |
        Write-Host "=== STARTING CLOUDFLARE TUNNEL ==="
        Write-Host "🎉 SETUP COMPLETE! 🎉"
        Write-Host ""
        Write-Host "📋 RDP CONNECTION DETAILS:"
        Write-Host "   Username: $env:RDP_USER"
        Write-Host "   Password: $env:RDP_PASSWORD"
        Write-Host ""
        Write-Host "📦 FILES DOWNLOADED:"
        Write-Host "   ✅ MuMu_Installer.exe - MuMu Android Emulator"
        Write-Host "   ✅ Android_Device.mumudata - MuMu data file"
        Write-Host ""
        Write-Host "🚀 SYSTEM OPTIMIZATIONS APPLIED:"
        Write-Host "   ✅ Virtualization Enabled"
        Write-Host "   ✅ High Performance Power Plan"
        Write-Host "   ✅ 8GB-16GB Virtual Memory"
        Write-Host "   ✅ RDP Graphics Optimized"
        Write-Host ""
        Write-Host "🔧 MANUAL INSTALLATION REQUIRED:"
        Write-Host "   After connecting via RDP:"
        Write-Host "   1. Run 'MuMu_Installer.exe' to install MuMu"
        Write-Host "   2. Use 'Android_Device.mumudata' as needed"
        Write-Host ""
        Write-Host "🌐 STARTING CLOUDFLARE TUNNEL..."
        Write-Host "   The RDP connection URL will appear below shortly"
        Write-Host "   This will keep running to maintain your RDP access"
        Write-Host ""
        Write-Host "⚠️  IMPORTANT: DO NOT STOP THIS WORKFLOW!"
        Write-Host "   Stopping will terminate your RDP connection"
        Write-Host ""
        
        # Start cloudflared tunnel in the FOREGROUND to see the URL and keep it running
        .\cloudflared.exe tunnel --url rdp://localhost:3389
